name = "authgate-login-worker"
main = "src/worker.js"
compatibility_date = "2023-11-07"
env = { }

[triggers]
crons = [ ]

[[migrations]]
tag = "v1"
new_classes = ["Fetcher"]

[[durable_objects.bindings]]
name = "authgate_login_worker"
class_name = "Fetcher"
